### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by sunshichao0916** [CartwrightLab/SoFoS#13]
Hi,
    I download SoFos from Github, but I don't know how to install, can you give me some suggestions? 
    
   Thanks.

**Comment by reedacartwright** [comment]
`cd` to the SoFoS directory and type `make` to compile SoFoS. This assumes that you have a compiler installed and are familiar with compiling software from the command line.

**Comment by sunshichao0916** [comment]
thanks for your answer, I upgrade my compiling software and installed sofos well now.  However, when I ran my date with follow commands, three populations have the same observed value.
`SoFoS-master/sofos -n 200 -u -t -a 1.0 -b 1.0  Landrace_input1.vcf  >Landrace.daf
SoFoS-master/sofos -n 200 -u -t -a 1.0 -b 1.0 Improved_input1.vcf  >Improved.daf
SoFoS-master/sofos -n 200 -u -t -a 1.0 -b 1.0 G.soja_input1.vcf  >G.soja.daf`

![Rplot](https://user-images.githubusercontent.com/70623629/116070592-6649a980-a6bf-11eb-885b-daa1a1b6ee6f.png)

Best

Sun

**Comment by reedacartwright** [comment]
I'd have to see how your input VCF is annotated and what your outputs look like. I suspect that SoFoS isn't able to identify any data in the VCFs and is returning a histogram using only the prior. Or you are reading the wrong column in the output.

**Comment by sunshichao0916** [comment]
The input VCF : 
`#fileformat=VCFv4.2
##INFO=<ID=AA,Number=1,Type=String,Description="Ancestral Allele">
##INFO=<ID=AAQ,Number=1,Type=Integer,Description="AA Quality">
###INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes">
###INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read depth">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype quality">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=PGT,Number=1,Type=String,Description="Physical phasing haplotype information, describing how the alternate alleles are phased in relation to one
##FORMAT=<ID=PID,Number=1,Type=String,Description="Physical phasing ID information, where each unique ID within a given sample (but not across samples) conne
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="The phred-scaled genotype likelihoods rounded to the closest integer">
##GATKCommandLine.CombineGVCFs=<ID=CombineGVCFs,Version=3.8-0-ge9d806836,Date="Sat Sep 02 15:42:51 CST 2017",Epoch=1504338171259,CommandLineOptions="analysis
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele frequency, for each ALT allele, in the same order as listed">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=BaseQRankSum,Number=1,Type=Float,Description="Z-score from Wilcoxon rank sum test of Alt Vs. Ref base qualities">
##INFO=<ID=ClippingRankSum,Number=1,Type=Float,Description="Z-score From Wilcoxon rank sum test of Alt vs. Ref number of hard clipped bases">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Combined depth across samples">
##INFO=<ID=DS,Number=0,Type=Flag,Description="Were any of the samples downsampled?">
##INFO=<ID=ExcessHet,Number=1,Type=Float,Description="Phred-scaled p-value for exact test of excess heterozygosity">
##INFO=<ID=FS,Number=1,Type=Float,Description="Phred-scaled p-value using Fisher's exact test to detect strand bias">
##INFO=<ID=HaplotypeScore,Number=1,Type=Float,Description="Consistency of the site with at most two segregating haplotypes">
##INFO=<ID=InbreedingCoeff,Number=1,Type=Float,Description="Inbreeding coefficient as estimated from the genotype likelihoods per-sample when compared agains
##INFO=<ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts, for each ALT allele, in the same order as lis
##INFO=<ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency, for each ALT allele, in the same order as li
##INFO=<ID=MQ,Number=1,Type=Float,Description="RMS mapping quality">
##INFO=<ID=MQRankSum,Number=1,Type=Float,Description="Z-score From Wilcoxon rank sum test of Alt vs. Ref read mapping qualities">
##INFO=<ID=QD,Number=1,Type=Float,Description="Variant Confidence/Quality by Depth">
##INFO=<ID=ReadPosRankSum,Number=1,Type=Float,Description="Z-score from Wilcoxon rank sum test of Alt vs. Ref read position bias">
##INFO=<ID=SOR,Number=1,Type=Float,Description="Symmetric Odds Ratio of 2x2 contingency table to detect strand bias">
##SentieonCommandLine.GVCFtyper=<ID=GVCFtyper,Version="sentieon-genomics-201704.03",Date="2017-11-23T02:26:02Z",CommandLine="/PUBLIC/software/RESEQ/software/
##SentieonCommandLine.Haplotyper=<ID=Haplotyper,Version="sentieon-genomics-201704.03",Date="2017-10-20T04:41:53Z",CommandLine="/PUBLIC/software/RESEQ/softwar
##contig=<ID= 1,length=56831624,assembly=unknown>
##contig=<ID= 2,length=48577505,assembly=unknown>
##contig=<ID= 3,length=45779781,assembly=unknown>
##contig=<ID= 4,length=52389146,assembly=unknown>
##contig=<ID= 5,length=42234498,assembly=unknown>
##contig=<ID= 6,length=51416486,assembly=unknown>
##contig=<ID= 7,length=44630646,assembly=unknown>
##contig=<ID= 8,length=47837940,assembly=unknown>
##contig=<ID= 9,length=50189764,assembly=unknown>
##contig=<ID= 7,length=44630646,assembly=unknown>
##contig=<ID= 8,length=47837940,assembly=unknown>
##contig=<ID= 9,length=50189764,assembly=unknown>
##contig=<ID= 10,length=51566898,assembly=unknown>
##contig=<ID= 11,length=34766867,assembly=unknown>
##contig=<ID= 12,length=40091314,assembly=unknown>
##contig=<ID= 13,length=45874162,assembly=unknown>
##contig=<ID= 14,length=49042192,assembly=unknown>
##contig=<ID= 15,length=51756343,assembly=unknown>
##contig=<ID= 16,length=37887014,assembly=unknown>
##contig=<ID= 17,length=41641366,assembly=unknown>
##contig=<ID= 18,length=58018742,assembly=unknown>
##contig=<ID= 19,length=50746916,assembly=unknown>
##contig=<ID= 20,length=47904181,assembly=unknown>
##reference=file:///TJPROJ2/RESEQ/Project_Crop/Crop3/luhongfeng/P101SC17040637-01_2000_soybean/V2/Gmax_275_v2.0.softmasked.20140305.fa
##reference=file:///ifs/TXPROJ05/P101SC17040637-01_dadou/ref/ref.fa
##reference=file:///TJPROJ2/RESEQ/share/database/Genomes/Plant/DaDou_Glycine_max/V2/Gmax_275_v2.0.softmasked.20140305.fa
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  16NF3865_3866   16NF3871_3872   16NF3881_3882   16NF3919_3920   16NF3975_3976   16NF3
1       1009547 1_1009547       G       A       359043  .       AA=A;AC=3236;AF=0.675;AN=4796;BaseQRankSum=0.598;ClippingRankSum=0.000;DP=13556;ExcessHet=-0. 0000;FS=0.000;InbreedingCoeff=0.8197;MLEAC=3342;MLEAF=0.697;MQ=59.36;0.000;QD=38.53;ReadPosRankSum=0.210;SOR=0.787       GT:AD:DP:GQ:PGT:PID:PL    1/1     1/1     1/1     1/1
......`

Output file:
`#SoFoS v2.0
#date=2021-04-27T11:32:47+0800
#epoch=1619494367493
#path=Landrace_input1.vcf
#alpha=1
#beta=1
#size=200
#folded=0
#refalt=0
#
## [8.8690s elapsed] 86455 sites processed
Number,Prior,Observed,Posterior
0,430.12437810894545,0,1363.8396483192903
1,430.12437810894545,0,3546.897323349519
2,430.12437810894545,6731,5029.5065004578264
3,430.12437810894545,8451,5283.6880266265571
4,430.12437810894545,5541,4722.5882178600041
5,430.12437810894545,4055,3901.6394639165419
6,430.12437810894545,3009,3138.8508718998137
7,430.12437810894545,2434,2533.3283696181707
8,430.12437810894545,1944,2080.089430938282
9,430.12437810894545,1604,1745.7523549941648
10,430.12437810894545,1396,1498.0852757217547
11,430.12437810894545,1194,1312.5046701475826
12,430.12437810894545,1042,1171.2863673775701
13,430.12437810894545,1053,1061.7064469530501
14,430.12437810894545,962,974.63489541170907
15,430.12437810894545,931,903.61099501299054`

The three output files are the same. It's very likely that sofos can't identify my VCFs, but I don't know what's wrong.

Thank you!

**Comment by reedacartwright** [comment]
Your prior is flat, so it's clearly detecting something because the posterior is not flat. I suspect that your input files might be accidentally identical or there is something else wrong in your pipeline.

**Comment by sunshichao0916** [comment]
Hi, 
I changed the INFO column of my input file,  just leave "AA=" information, the results seems to be correct.

Thank you for your nice help.

best,

Sun
