### ISSUE TITLE
multiallelic data

### ISSUE THREAD

**Issue by oushujun** [CartwrightLab/SoFoS#19]
Hello,

I am trying to apply SoFoS on triallelic data and calculate folded SFS on a designated allele. I used the v2.0 on such data and encounter an error:
>#SoFoS v2.0
#date=2021-12-15T17:41:07-0600
#epoch=1639611667475
#path=synLTR.triAllelic.vcf
#alpha=1
#beta=1
#size=10
#folded=0
#refalt=1
[E::bcf_calc_ac] Incorrect allele ("2") in Ki11 at 1:1

If all loci are triallelic homozygous, i.e., 0/0 (ref), 1/1, and 2/2, and I want to estimate folded SFS on allele 1, is there a way to do so? Is it equivalent to converting 2s to 0s, and estimating the folded SFS for 0s and 1s?

Thanks,
Shujun

**Comment by reedacartwright** [comment]
It sounds like your VCF is not formatted as SoFoS expectes.  Can you share with us a few lines of it?
@jporton Can you help investigate this issue?

**Comment by oushujun** [comment]
Hi @reedacartwright, 

Thanks for the instant response. [test.vcf.zip](https://github.com/CartwrightLab/SoFoS/files/7723740/test.vcf.zip) is a sample of my vcf. All loci are homozygous and most are triallelic. I used these parameters: `sofos -n 10 -f -r -a 1.0 -b 1.0 test.vcf`

Thanks,
Shujun

**Comment by jporton** [comment]
Hi @oushujun, 
Taking a look at the vcf you shared it appears that you have two reference alleles called here which is causing this issue.

**Comment by oushujun** [comment]
Hi @jporton,

Thank you for looking into this quickly! Yes, I did mistakenly assign two ref alleles instead of two alt alleles. After fixing this, SoFoS runs without an issue.

I need your help to interpret the result though. So for unfoled SFS, all alternative alleles are combined as derived, correct? For folded SFS, which is to calculate the minor allele frequency, does it always report the least frequent allele of among the multiple alleles? For example, what MAF will be for ref, alt1, and alt2 frequencies 0.1, 0.2, 0.7, and 0.4, 0.3, 0.3?

Thanks again!
Shujun

**Comment by jporton** [comment]
SoFoS contrasts the "ancestral" allele with all other alleles pooled, for both folded and unfolded. Ancestral allele being defined by the tag -r or -t.

**Comment by oushujun** [comment]
@jporton  Thank you for your clear explanation and instant help!
